/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCurso;

/**
 *
 * @author dkmrfcb
 */
public class GUICurso extends javax.swing.JFrame {

    /**
     * Creates new form GUICurso
     */
    public GUICurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldNombreCurso = new javax.swing.JTextField();
        fieldSiglasCurso = new javax.swing.JTextField();
        fieldCreditosCurso = new javax.swing.JTextField();
        labelNombreCurso = new javax.swing.JLabel();
        labelSiglasCurso = new javax.swing.JLabel();
        labelCreditosCurso = new javax.swing.JLabel();
        botonRegistrarCurso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 209, 54));

        jLabel1.setFont(new java.awt.Font("Free Avant Garde Medium", 0, 18)); // NOI18N
        jLabel1.setText("Registrar Cursos");

        fieldCreditosCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCreditosCursoActionPerformed(evt);
            }
        });

        labelNombreCurso.setText("Nombre del curso");

        labelSiglasCurso.setText("Siglas del curso");

        labelCreditosCurso.setText("Créditos del curso");

        botonRegistrarCurso.setText("Registrar");
        botonRegistrarCurso.setActionCommand("BOTONREGISTRARCURSO");
        botonRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarCursoActionPerformed(evt);
            }
        });

        jLabel2.setText("sdfsdfsdfjnsdfknjdsfnsdf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNombreCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSiglasCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCreditosCurso, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(fieldSiglasCurso)
                                    .addComponent(fieldCreditosCurso)))
                            .addComponent(botonRegistrarCurso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNombreCurso)
                                    .addComponent(fieldNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelSiglasCurso)
                                .addComponent(fieldSiglasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCreditosCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCreditosCurso, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrarCurso)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCreditosCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCreditosCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCreditosCursoActionPerformed

    private void botonRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarCursoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarCurso;
    private javax.swing.JTextField fieldCreditosCurso;
    private javax.swing.JTextField fieldNombreCurso;
    private javax.swing.JTextField fieldSiglasCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCreditosCurso;
    private javax.swing.JLabel labelNombreCurso;
    private javax.swing.JLabel labelSiglasCurso;
    // End of variables declaration//GEN-END:variables

    public static final String BOTON_REGISTRAR_CURSO = "BOTONREGISTRARCURSO";

    public String getFieldNombreCurso (){
        return this.fieldNombreCurso.getText().toString().trim();
    }
    
    public void setFieldNombreCurso(String nombreCurso){
        this.fieldNombreCurso.setText(nombreCurso);
    }
    
    public String getFieldSiglasCurso (){
        return this.fieldSiglasCurso.getText().toString().trim();
    }
    
    public void setFieldSiglasCurso(String siglasCurso){
        this.fieldSiglasCurso.setText(siglasCurso);
    }
    
    public int getFieldCreditosCurso (){
        
        if (this.fieldCreditosCurso.getText().equalsIgnoreCase("")){
            return 0;
            
        }else {
            
        return Integer.parseInt (this.fieldCreditosCurso.getText());
        }
        
    }
    
    public void setFieldCreditosCurso(int creditosCurso){
        this.fieldCreditosCurso.setText (""+creditosCurso);
    }
    public void limpiar() {
        
        this.fieldNombreCurso.setText(""); 
        this.fieldSiglasCurso.setText("");
        this.fieldCreditosCurso.setText("");
    }
    
    public void escuchar(ControladorCurso controladorCurso){
        
        botonRegistrarCurso.addActionListener(controladorCurso);
    }
}
